"""version1.1

Revision ID: 0910d83a8c4d
Revises: ccdfdabcb326
Create Date: 2016-03-02 16:40:42.592078

"""

# revision identifiers, used by Alembic.
revision = '0910d83a8c4d'
down_revision = 'ccdfdabcb326'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
