"""version1.4

Revision ID: 68d4bfa7a000
Revises: cba9682151ed
Create Date: 2016-03-02 17:10:32.087437

"""

# revision identifiers, used by Alembic.
revision = '68d4bfa7a000'
down_revision = 'cba9682151ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
